//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
//using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Data;
using LinqToDB.DataProvider.SqlServer;
using LinqToDB.Extensions;
using LinqToDB.Mapping;

namespace DataModel
{
    /// <summary>
    /// Database       : AutorizadorCN
    /// Data Source    : .\SQLEXPRESS
    /// Server Version : 12.00.2269
    /// </summary>
    public partial class AutorizadorCNDB : LinqToDB.Data.DataConnection
    {
        public ITable<I_Batch> I_Batch { get { return this.GetTable<I_Batch>(); } }
        public ITable<i_patch> i_patch { get { return this.GetTable<i_patch>(); } }
        public ITable<I_Scheduler> I_Scheduler { get { return this.GetTable<I_Scheduler>(); } }
        public ITable<LINK_Agendum> LINK_Agenda { get { return this.GetTable<LINK_Agendum>(); } }
        public ITable<LINK_Edu_FundoEmpresa> LINK_Edu_FundoEmpresa { get { return this.GetTable<LINK_Edu_FundoEmpresa>(); } }
        public ITable<LINK_LojaEmpresa> LINK_LojaEmpresa { get { return this.GetTable<LINK_LojaEmpresa>(); } }
        public ITable<LINK_PFAtivacao> LINK_PFAtivacao { get { return this.GetTable<LINK_PFAtivacao>(); } }
        public ITable<LINK_ProprietarioCartao> LINK_ProprietarioCartao { get { return this.GetTable<LINK_ProprietarioCartao>(); } }
        public ITable<LINK_RepasseParcela> LINK_RepasseParcela { get { return this.GetTable<LINK_RepasseParcela>(); } }
        public ITable<LINK_UsuarioTerminal> LINK_UsuarioTerminal { get { return this.GetTable<LINK_UsuarioTerminal>(); } }
        public ITable<LOG_Audit> LOG_Audit { get { return this.GetTable<LOG_Audit>(); } }
        public ITable<EmpresaDespesa> EmpresaDespesa { get { return this.GetTable<EmpresaDespesa>(); } }
        public ITable<EmpresaDespesaRecorrente> EmpresaDespesaRecorrente { get { return this.GetTable<EmpresaDespesaRecorrente>(); } }
        public ITable<LancamentosCC> LancamentosCC { get { return this.GetTable<LancamentosCC>(); } }
        public ITable<LOG_Chamado> LOG_Chamado { get { return this.GetTable<LOG_Chamado>(); } }
        public ITable<LOG_Edu_RendimentoEmpresa> LOG_Edu_RendimentoEmpresa { get { return this.GetTable<LOG_Edu_RendimentoEmpresa>(); } }
        public ITable<LOG_Fechamento> LOG_Fechamento { get { return this.GetTable<LOG_Fechamento>(); } }
        public ITable<LOG_GiftRange> LOG_GiftRanges { get { return this.GetTable<LOG_GiftRange>(); } }
        public ITable<LOG_NS_FAT> LOG_NS_FAT { get { return this.GetTable<LOG_NS_FAT>(); } }
        public ITable<LOG_NSA> LOG_NSA { get { return this.GetTable<LOG_NSA>(); } }
        public ITable<LOG_NSU> LOG_NSU { get { return this.GetTable<LOG_NSU>(); } }
        public ITable<LOG_Transaco> LOG_Transacoes { get { return this.GetTable<LOG_Transaco>(); } }
        public ITable<LOG_VendaCartaoGift> LOG_VendaCartaoGift { get { return this.GetTable<LOG_VendaCartaoGift>(); } }
        public ITable<LOG_VendaProdutoGift> LOG_VendaProdutoGift { get { return this.GetTable<LOG_VendaProdutoGift>(); } }
        public ITable<T_BoletoEdu> T_BoletoEdu { get { return this.GetTable<T_BoletoEdu>(); } }
        public ITable<T_Cartao> T_Cartao { get { return this.GetTable<T_Cartao>(); } }
        public ITable<T_Chamado> T_Chamado { get { return this.GetTable<T_Chamado>(); } }
        public ITable<T_ChequesGift> T_ChequesGift { get { return this.GetTable<T_ChequesGift>(); } }
        public ITable<T_Dependente> T_Dependente { get { return this.GetTable<T_Dependente>(); } }
        public ITable<T_Edu_AplicacaoVirtual> T_Edu_AplicacaoVirtual { get { return this.GetTable<T_Edu_AplicacaoVirtual>(); } }
        public ITable<T_Edu_EmpresaVirtual> T_Edu_EmpresaVirtual { get { return this.GetTable<T_Edu_EmpresaVirtual>(); } }
        public ITable<T_JobFechamento> T_JobFechamento { get { return this.GetTable<T_JobFechamento>(); } }
        public ITable<T_Edu_FundoEmpresa> T_Edu_FundoEmpresa { get { return this.GetTable<T_Edu_FundoEmpresa>(); } }
        public ITable<T_Empresa> T_Empresa { get { return this.GetTable<T_Empresa>(); } }
        public ITable<T_EmpresaAfiliada> T_EmpresaAfiliada { get { return this.GetTable<T_EmpresaAfiliada>(); } }
        public ITable<T_ExtraGift> T_ExtraGift { get { return this.GetTable<T_ExtraGift>(); } }
        public ITable<T_Faturamento> T_Faturamento { get { return this.GetTable<T_Faturamento>(); } }
        public ITable<T_FaturamentoDetalhe> T_FaturamentoDetalhes { get { return this.GetTable<T_FaturamentoDetalhe>(); } }
        public ITable<T_InfoAdicionai> T_InfoAdicionais { get { return this.GetTable<T_InfoAdicionai>(); } }
        public ITable<T_Loja> T_Loja { get { return this.GetTable<T_Loja>(); } }
        public ITable<T_LojaMensagem> T_LojaMensagem { get { return this.GetTable<T_LojaMensagem>(); } }
        public ITable<T_LoteCartao> T_LoteCartao { get { return this.GetTable<T_LoteCartao>(); } }
        public ITable<T_LoteCartaoDetalhe> T_LoteCartaoDetalhe { get { return this.GetTable<T_LoteCartaoDetalhe>(); } }
        public ITable<T_MensagemEdu> T_MensagemEdu { get { return this.GetTable<T_MensagemEdu>(); } }
        public ITable<T_Parcela> T_Parcelas { get { return this.GetTable<T_Parcela>(); } }
        public ITable<T_PayFone> T_PayFone { get { return this.GetTable<T_PayFone>(); } }
        public ITable<T_PendPayFone> T_PendPayFone { get { return this.GetTable<T_PendPayFone>(); } }
        public ITable<T_Proprietario> T_Proprietario { get { return this.GetTable<T_Proprietario>(); } }
        public ITable<T_Quiosque> T_Quiosque { get { return this.GetTable<T_Quiosque>(); } }
        public ITable<T_RepasseLoja> T_RepasseLoja { get { return this.GetTable<T_RepasseLoja>(); } }
        public ITable<T_RetCobranca> T_RetCobranca { get { return this.GetTable<T_RetCobranca>(); } }
        public ITable<T_Terminal> T_Terminal { get { return this.GetTable<T_Terminal>(); } }
        public ITable<T_Usuario> T_Usuario { get { return this.GetTable<T_Usuario>(); } }
        public ITable<T_WebBlock> T_WebBlock { get { return this.GetTable<T_WebBlock>(); } }
        public ITable<T_SaldoConvenio> T_SaldoConvenio { get { return this.GetTable<T_SaldoConvenio>(); } }
        public ITable<Parceiro> Parceiro { get { return this.GetTable<Parceiro>(); } }
        public ITable<UsuarioParceiro> UsuarioParceiro { get { return this.GetTable<UsuarioParceiro>(); } }

        public ITable<DashboardGrafico> DashboardGrafico { get { return this.GetTable<DashboardGrafico>(); } }

        public ITable<ConfigPlasticoEnvio> ConfigPlasticoEnvio { get { return this.GetTable<ConfigPlasticoEnvio>(); } }

        public AutorizadorCNDB()
        {
            InitDataContext();
        }

        public AutorizadorCNDB(string configuration)
            : base(configuration)
        {
            InitDataContext();
        }

        partial void InitDataContext();

        #region FreeTextTable

        public class FreeTextKey<T>
        {
            public T Key;
            public int Rank;
        }

        private static MethodInfo _freeTextTableMethod1 = typeof(AutorizadorCNDB).GetMethod("FreeTextTable", new Type[] { typeof(string), typeof(string) });

        [FreeTextTableExpression]
        public ITable<FreeTextKey<TKey>> FreeTextTable<TTable, TKey>(string field, string text)
        {
            return this.GetTable<FreeTextKey<TKey>>(
                this,
                _freeTextTableMethod1,
                field,
                text);
        }

        private static MethodInfo _freeTextTableMethod2 =
            typeof(AutorizadorCNDB).GetMethods()
                .Where(m => m.Name == "FreeTextTable" && m.IsGenericMethod && m.GetParameters().Length == 2)
                .Where(m => m.GetParameters()[0].ParameterType.IsGenericTypeEx() && m.GetParameters()[0].ParameterType.GetGenericTypeDefinition() == typeof(Expression<>))
                .Where(m => m.GetParameters()[1].ParameterType == typeof(string))
                .Single();

        [FreeTextTableExpression]
        public ITable<FreeTextKey<TKey>> FreeTextTable<TTable, TKey>(Expression<Func<TTable, string>> fieldSelector, string text)
        {
            return this.GetTable<FreeTextKey<TKey>>(
                this,
                _freeTextTableMethod2,
                fieldSelector,
                text);
        }

        #endregion
    }

    [Table(Schema = "dbo", Name = "EmpresaDespesa")]
    public partial class EmpresaDespesa
    {
        [PrimaryKey, Identity] public long id { get; set; }
        [Column, Nullable] public long? fkEmpresa { get; set; }
        [Column, Nullable] public string stCodigo { get; set; }
        [Column, Nullable] public string stDescricao { get; set; }    }

    [Table(Schema = "dbo", Name = "EmpresaDespesaRecorrente")]
    public partial class EmpresaDespesaRecorrente
    {
        [PrimaryKey, Identity] public long id { get; set; }
        [Column, Nullable] public long? fkEmpresa { get; set; }
        [Column, Nullable] public string stCodigo { get; set; }
        [Column, Nullable] public string stDescricao { get; set; }
        [Column, Nullable] public bool? bAtivo { get; set; }
    }

    [Table(Schema = "dbo", Name = "LancamentosCC")]
    public partial class LancamentosCC
    {
        [PrimaryKey, Identity] public long id { get; set; }
        [Column, Nullable] public long? fkEmpresa { get; set; }
        [Column, Nullable] public long? fkCartao { get; set; }
        [Column, Nullable] public long? nuMes { get; set; }
        [Column, Nullable] public long? nuAno { get; set; }
        [Column, Nullable] public long? fkTipo { get; set; }
        [Column, Nullable] public long? vrValor { get; set; }
        [Column, Nullable] public long? nuParcela { get; set; }
        [Column, Nullable] public long? nuTotParcelas { get; set; }
        [Column, Nullable] public bool? bRecorrente { get; set; }
    }

    [Table(Schema = "dbo", Name = "DashboardGrafico")]
    public partial class DashboardGrafico
    {
        [PrimaryKey, Identity] public long id { get; set; }
        [Column, Nullable] public int totalTransacoes { get; set; }
        [Column, Nullable] public int totalCartoes { get; set; }
        [Column, Nullable] public int totalFinanc { get; set; }
        [Column, Nullable] public int totalLojas { get; set; }
        [Column, Nullable] public int nuDia { get; set; }
        [Column, Nullable] public int nuMes { get; set; }
        [Column, Nullable] public int nuAno { get; set; }
        [Column, Nullable] public DateTime dtDia { get; set; }
    }

    [Table(Schema = "dbo", Name = "ConfigPlasticoEnvio")]
    public partial class ConfigPlasticoEnvio
    {
        [PrimaryKey, Identity] public long id { get; set; }
        [Column, Nullable] public string stDias { get; set; }
        [Column, Nullable] public string stHorario { get; set; }
        [Column, Nullable] public string stEmails { get; set; }
        [Column, Nullable] public bool? bAtivo { get; set; }
        [Column, Nullable] public bool? dom { get; set; }
        [Column, Nullable] public bool? seg { get; set; }
        [Column, Nullable] public bool? ter { get; set; }
        [Column, Nullable] public bool? qua { get; set; }
        [Column, Nullable] public bool? qui { get; set; }
        [Column, Nullable] public bool? sex { get; set; }
        [Column, Nullable] public bool? sab { get; set; }
        [Column, Nullable] public string stEmailSmtp { get; set; }
        [Column, Nullable] public string stSenhaSmtp { get; set; }
        [Column, Nullable] public string stHostSmtp { get; set; }
        [Column, Nullable] public int? nuPortSmtp { get; set; }
        [Column, Nullable] public string stStatus { get; set; }
    }

    [Table(Schema = "dbo", Name = "Parceiro")]
    public partial class Parceiro
    {
        [PrimaryKey, Identity] public long id { get; set; }
        [Column, Nullable] public string stNome { get; set; }
        [Column, Nullable] public DateTime? dtCadastro { get; set; }
        [Column, Nullable] public string stTelefone { get; set; }
        [Column, Nullable] public string stCelular { get; set; }
        [Column, Nullable] public string stResp { get; set; }
        [Column, Nullable] public string stSocial { get; set; }
        [Column, Nullable] public string stCNPJ { get; set; }
        [Column, Nullable] public string stEstado { get; set; }
        [Column, Nullable] public string stCidade { get; set; }
        [Column, Nullable] public string stEndereco { get; set; }
        [Column, Nullable] public string stCep { get; set; }
        [Column, Nullable] public string stObs { get; set; }
    }

    [Table(Schema = "dbo", Name = "UsuarioParceiro")]
    public partial class UsuarioParceiro
    {
        [PrimaryKey, Identity] public long id { get; set; }
        [Column, Nullable] public string stEmail { get; set; }
        [Column, Nullable] public string stSenha { get; set; }
        [Column, Nullable] public string stNome { get; set; }
        [Column, Nullable] public int nuTipo { get; set; }
        [Column, Nullable] public long fkParceiro { get; set; }
        [Column, Nullable] public bool bAtivo { get; set; }
        [Column, Nullable] public DateTime? dtCadastro { get; set; }
        [Column, Nullable] public DateTime? dtLastLogin { get; set; }
    }

    [Table(Schema = "dbo", Name = "T_SaldoConvenio")]
    public partial class T_SaldoConvenio
    {
        [PrimaryKey, Identity] public long i_unique { get; set; }
        [Column, Nullable] public long fk_cartao { get; set; }
        [Column, Nullable] public long vr_saldo { get; set; }
        [Column, Nullable] public long nu_mes { get; set; }
        [Column, Nullable] public long nu_ano { get; set; }
    }

    [Table(Schema = "dbo", Name = "T_JobFechamento")]
    public partial class T_JobFechamento
    {
        [PrimaryKey, Identity] public int i_unique { get; set; } 
        [Column, Nullable] public int fk_empresa { get; set; } 
        [Column, Nullable] public DateTime? dt_inicio { get; set; } 
        [Column, Nullable] public DateTime? dt_fim { get; set; } 
        [Column, Nullable] public string st_mes { get; set; }
        [Column, Nullable] public string st_ano { get; set; }
    }

    [Table(Schema = "dbo", Name = "I_Batch")]
    public partial class I_Batch
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public string st_archive { get; set; } // varchar(999)
        [Column, Nullable] public DateTime? dt_start { get; set; } // datetime
        [Column, Nullable] public DateTime? dt_proc_start { get; set; } // datetime
        [Column, Nullable] public DateTime? dt_proc_end { get; set; } // datetime
        [Column, Nullable] public char? tg_processed { get; set; } // varchar(1)
        [Column, Nullable] public char? tg_running { get; set; } // varchar(1)
    }

    [Table(Schema = "dbo", Name = "i_patch")]
    public partial class i_patch
    {
        [PrimaryKey, Identity] public int i_unique { get; set; } // int
        [Column, Nullable] public char? st_done { get; set; } // varchar(1)
    }

    [Table(Schema = "dbo", Name = "I_Scheduler")]
    public partial class I_Scheduler
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public string st_job { get; set; } // varchar(400)
        [Column, Nullable] public char? tg_type { get; set; } // varchar(1)
        [Column, Nullable] public DateTime? dt_specific { get; set; } // datetime
        [Column, Nullable] public string st_daily_hhmm { get; set; } // varchar(4)
        [Column, Nullable] public int? st_weekly_dow { get; set; } // int
        [Column, Nullable] public string st_weekly_hhmm { get; set; } // varchar(4)
        [Column, Nullable] public int? nu_monthly_day { get; set; } // int
        [Column, Nullable] public string st_monthly_hhmm { get; set; } // varchar(4)
        [Column, Nullable] public DateTime? dt_last { get; set; } // datetime
        [Column, Nullable] public char? tg_status { get; set; } // varchar(1)
        [Column, Nullable] public DateTime? dt_prev { get; set; } // datetime
    }

    [Table(Schema = "dbo", Name = "LINK_Agenda")]
    public partial class LINK_Agendum
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_schedule { get; set; } // int
        [Column, Nullable] public int? fk_empresa { get; set; } // int
        [Column, Nullable] public int? en_atividade { get; set; } // int
        [Column, Nullable] public string st_emp_afiliada { get; set; } // varchar(20)
    }

    [Table(Schema = "dbo", Name = "LINK_Edu_FundoEmpresa")]
    public partial class LINK_Edu_FundoEmpresa
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_cartao { get; set; } // int
        [Column, Nullable] public int? fk_empresa { get; set; } // int
        [Column, Nullable] public int? vr_fundo { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "LINK_LojaEmpresa")]
    public partial class LINK_LojaEmpresa
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_loja { get; set; } // int
        [Column, Nullable] public int? fk_empresa { get; set; } // int
        [Column, Nullable] public int? tx_admin { get; set; } // int
        [Column, Nullable] public int? nu_dias_repasse { get; set; } // int
        [Column, Nullable] public string st_ag { get; set; } // varchar(10)
        [Column, Nullable] public string st_conta { get; set; } // varchar(15)
        [Column, Nullable] public string st_banco { get; set; } // varchar(15)
    }

    [Table(Schema = "dbo", Name = "LINK_PFAtivacao")]
    public partial class LINK_PFAtivacao
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_payfone { get; set; } // int
        [Column, Nullable] public DateTime? dt_ativacao { get; set; } // datetime
        [Column, Nullable] public string st_ativacao { get; set; } // varchar(50)
        [Column, Nullable] public char? tg_status { get; set; } // varchar(1)
    }

    [Table(Schema = "dbo", Name = "LINK_ProprietarioCartao")]
    public partial class LINK_ProprietarioCartao
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_cartao { get; set; } // int
        [Column, Nullable] public int? fk_proprietario { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "LINK_RepasseParcela")]
    public partial class LINK_RepasseParcela
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_repasseLoja { get; set; } // int
        [Column, Nullable] public int? fk_parcela { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "LINK_UsuarioTerminal")]
    public partial class LINK_UsuarioTerminal
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_user { get; set; } // int
        [Column, Nullable] public int? fk_term { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "LOG_Audit")]
    public partial class LOG_Audit
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_usuario { get; set; } // int
        [Column, Nullable] public int? tg_operacao { get; set; } // int
        [Column, Nullable] public DateTime? dt_operacao { get; set; } // datetime
        [Column, Nullable] public string st_observacao { get; set; } // varchar(150)
        [Column, Nullable] public int? fk_generic { get; set; } // int
        [Column, Nullable] public string st_empresa { get; set; } // varchar(150)
        [Column, Nullable] public string st_oper { get; set; } // varchar(150)
        [Column, Nullable] public string st_log { get; set; } // varchar(150)
    }

    [Table(Schema = "dbo", Name = "LOG_Chamado")]
    public partial class LOG_Chamado
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_chamado { get; set; } // int
        [Column, Nullable] public int? fk_operador { get; set; } // int
        [Column, Nullable] public string st_solucao { get; set; } // varchar(900)
        [Column, Nullable] public DateTime? dt_solucao { get; set; } // datetime
    }

    [Table(Schema = "dbo", Name = "LOG_Edu_RendimentoEmpresa")]
    public partial class LOG_Edu_RendimentoEmpresa
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_empresaVirtual { get; set; } // int
        [Column, Nullable] public int? vr_pct { get; set; } // int
        [Column, Nullable] public DateTime? dt_rend { get; set; } // datetime
        [Column, Nullable] public char? tg_neg { get; set; } // varchar(1)
    }

    [Table(Schema = "dbo", Name = "LOG_Fechamento")]
    public partial class LOG_Fechamento
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public string st_mes { get; set; } // varchar(2)
        [Column, Nullable] public string st_ano { get; set; } // varchar(4)
        [Column, Nullable] public int? vr_valor { get; set; } // int
        [Column, Nullable] public DateTime? dt_fechamento { get; set; } // datetime
        [Column, Nullable] public int? fk_empresa { get; set; } // int
        [Column, Nullable] public int? fk_loja { get; set; } // int
        [Column, Nullable] public int? fk_cartao { get; set; } // int
        [Column, Nullable] public int? fk_parcela { get; set; } // int
        [Column, Nullable] public DateTime? dt_compra { get; set; } // datetime
        [Column, Nullable] public int? nu_parcela { get; set; } // int
        [Column, Nullable] public string st_cartao { get; set; } // varchar(14)
        [Column, Nullable] public string st_afiliada { get; set; } // varchar(20)
    }

    [Table(Schema = "dbo", Name = "LOG_GiftRanges")]
    public partial class LOG_GiftRange
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_empresa { get; set; } // int
        [Column, Nullable] public int? nu_inicio { get; set; } // int
        [Column, Nullable] public int? nu_fim { get; set; } // int
        [Column, Nullable] public DateTime? dt_requisicao { get; set; } // datetime
    }

    [Table(Schema = "dbo", Name = "LOG_NS_FAT")]
    public partial class LOG_NS_FAT
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public DateTime? dt_log { get; set; } // datetime
    }

    [Table(Schema = "dbo", Name = "LOG_NSA")]
    public partial class LOG_NSA
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public DateTime? dt_log { get; set; } // datetime
    }

    [Table(Schema = "dbo", Name = "LOG_NSU")]
    public partial class LOG_NSU
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public DateTime? dt_log { get; set; } // datetime
    }

    [Table(Schema = "dbo", Name = "LOG_Transacoes")]
    public partial class LOG_Transaco
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_terminal { get; set; } // int
        [Column, Nullable] public DateTime? dt_transacao { get; set; } // datetime
        [Column, Nullable] public int? nu_nsu { get; set; } // int
        [Column, Nullable] public int? fk_empresa { get; set; } // int
        [Column, Nullable] public int? fk_cartao { get; set; } // int
        [Column, Nullable] public int? vr_total { get; set; } // int
        [Column, Nullable] public int? nu_parcelas { get; set; } // int
        [Column, Nullable] public int? nu_cod_erro { get; set; } // int
        [Column, Nullable] public char? tg_confirmada { get; set; } // varchar(1)
        [Column, Nullable] public int? nu_nsuOrig { get; set; } // int
        [Column, Nullable] public string en_operacao { get; set; } // varchar(10)
        [Column, Nullable] public string st_msg_transacao { get; set; } // varchar(50)
        [Column, Nullable] public char? tg_contabil { get; set; } // varchar(1)
        [Column, Nullable] public int? fk_loja { get; set; } // int
        [Column, Nullable] public int? vr_saldo_disp { get; set; } // int
        [Column, Nullable] public int? vr_saldo_disp_tot { get; set; } // int
        [Column, Nullable] public string st_doc { get; set; } // varchar(20)
    }

    [Table(Schema = "dbo", Name = "LOG_VendaCartaoGift")]
    public partial class LOG_VendaCartaoGift
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_vendedor { get; set; } // int
        [Column, Nullable] public int? fk_empresa { get; set; } // int
        [Column, Nullable] public int? fk_cartao { get; set; } // int
        [Column, Nullable] public int? tg_tipoPag { get; set; } // int
        [Column, Nullable] public DateTime? dt_compra { get; set; } // datetime
        [Column, Nullable] public int? tg_tipoCartao { get; set; } // int
        [Column, Nullable] public string st_cheque { get; set; } // varchar(80)
        [Column, Nullable] public int? nu_nsuCartao { get; set; } // int
        [Column, Nullable] public int? vr_carga { get; set; } // int
        [Column, Nullable] public int? tg_adesao { get; set; } // int
        [Column, Nullable] public string st_codImpresso { get; set; } // varchar(90)
    }

    [Table(Schema = "dbo", Name = "LOG_VendaProdutoGift")]
    public partial class LOG_VendaProdutoGift
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_vendaCartao { get; set; } // int
        [Column, Nullable] public string st_produto { get; set; } // varchar(90)
        [Column, Nullable] public int? vr_valor { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "T_BoletoEdu")]
    public partial class T_BoletoEdu
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public DateTime? dt_emissao { get; set; } // datetime
        [Column, Nullable] public int? vr_imediato { get; set; } // int
        [Column, Nullable] public int? vr_educacional { get; set; } // int
        [Column, Nullable] public int? fk_cartao { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "T_Cartao")]
    public partial class T_Cartao
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public string st_empresa { get; set; } // varchar(6)
        [Column, Nullable] public string st_matricula { get; set; } // varchar(6)
        [Column, Nullable] public string st_titularidade { get; set; } // varchar(2)
        [Column, Nullable] public string st_senha { get; set; } // varchar(16)
        [Column, Nullable] public char? tg_tipoCartao { get; set; } // varchar(1)
        [Column, Nullable] public string st_venctoCartao { get; set; } // varchar(4)
        [Column, Nullable] public char? tg_status { get; set; } // varchar(1)
        [Column, Nullable] public DateTime? dt_utlPagto { get; set; } // datetime
        [Column, Nullable] public int? nu_senhaErrada { get; set; } // int
        [Column, Nullable] public DateTime? dt_inclusao { get; set; } // datetime
        [Column, Nullable] public DateTime? dt_bloqueio { get; set; } // datetime
        [Column, Nullable] public char? tg_motivoBloqueio { get; set; } // varchar(1)
        [Column, Nullable] public string st_banco { get; set; } // varchar(4)
        [Column, Nullable] public string st_agencia { get; set; } // varchar(4)
        [Column, Nullable] public string st_conta { get; set; } // varchar(10)
        [Column, Nullable] public string st_matriculaExtra { get; set; } // varchar(10)
        [Column, Nullable] public string st_celCartao { get; set; } // varchar(13)
        [Column, Nullable] public int? fk_dadosProprietario { get; set; } // int
        [Column, Nullable] public int? fk_infoAdicionais { get; set; } // int
        [Column, Nullable] public int? nu_viaCartao { get; set; } // int
        [Column, Nullable] public int? vr_limiteTotal { get; set; } // int
        [Column, Nullable] public int? vr_limiteMensal { get; set; } // int
        [Column, Nullable] public int? vr_limiteRotativo { get; set; } // int
        [Column, Nullable] public int? vr_extraCota { get; set; } // int
        [Column, Nullable] public int? vr_educacional { get; set; } // int
        [Column, Nullable] public int? vr_disp_educacional { get; set; } // int
        [Column, Nullable] public int? vr_edu_diario { get; set; } // int
        [Column, Nullable] public string st_aluno { get; set; } // varchar(40)
        [Column, Nullable] public int? tg_emitido { get; set; } // int
        [Column, Nullable] public int? vr_edu_disp_virtual { get; set; } // int
        [Column, Nullable] public int? nu_rankVirtual { get; set; } // int
        [Column, Nullable] public int? vr_edu_total_ranking { get; set; } // int
        [Column, Nullable] public int? nu_webSenhaErrada { get; set; } // int
        [Column, Nullable] public int? tg_semanaCompleta { get; set; } // int
        [Column, Nullable] public int? tg_excluido { get; set; } // int
        [Column, Nullable] public bool? tg_convenioComSaldo { get; set; }
        [Column, Nullable] public long? vr_saldoConvenio { get; set; }

        [Column, Nullable] public DateTime? dtPedidoCartao { get; set; }
        [Column, Nullable] public string stCodigoFOPA { get; set; } // varchar(40)
    }

    [Table(Schema = "dbo", Name = "T_Chamado")]
    public partial class T_Chamado
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_loja { get; set; } // int
        [Column, Nullable] public int? tg_fechado { get; set; } // int
        [Column, Nullable] public int? fk_operador { get; set; } // int
        [Column, Nullable] public int? nu_prioridade { get; set; } // int
        [Column, Nullable] public int? nu_categoria { get; set; } // int
        [Column, Nullable] public DateTime? dt_abertura { get; set; } // datetime
        [Column, Nullable] public DateTime? dt_fechamento { get; set; } // datetime
        [Column, Nullable] public string st_motivo { get; set; } // varchar(900)
        [Column, Nullable] public int? tg_tecnico { get; set; } // int
        [Column, Nullable] public int? fk_oper_criador { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "T_ChequesGift")]
    public partial class T_ChequesGift
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public string st_identificador { get; set; } // varchar(40)
        [Column, Nullable] public int? fk_cartao { get; set; } // int
        [Column, Nullable] public DateTime? dt_efetiva { get; set; } // datetime
        [Column, Nullable] public int? tg_compensado { get; set; } // int
        [Column, Nullable] public int? vr_valor { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "T_Dependente")]
    public partial class T_Dependente
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? nu_titularidade { get; set; } // int
        [Column, Nullable] public string st_nome { get; set; } // varchar(40)
        [Column, Nullable] public int? fk_proprietario { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "T_Edu_AplicacaoVirtual")]
    public partial class T_Edu_AplicacaoVirtual
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_cartao { get; set; } // int
        [Column, Nullable] public int? fk_empresaVirtual { get; set; } // int
        [Column, Nullable] public int? vr_aplicado { get; set; } // int
        [Column, Nullable] public DateTime? dt_aplic { get; set; } // datetime
        [Column, Nullable] public char? tg_neg { get; set; } // varchar(1)
        [Column, Nullable] public int? vr_fundo_hora { get; set; } // int
        [Column, Nullable] public int? vr_preco_fundo { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "T_Edu_EmpresaVirtual")]
    public partial class T_Edu_EmpresaVirtual
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public string st_nome { get; set; } // varchar(99)
        [Column, Nullable] public string st_codigo { get; set; } // varchar(20)
        [Column, Nullable] public int? vr_valorAcao { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "T_Edu_FundoEmpresa")]
    public partial class T_Edu_FundoEmpresa
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_cartao { get; set; } // int
        [Column, Nullable] public int? fk_empresaVirtual { get; set; } // int
        [Column, Nullable] public int? vr_fundo { get; set; } // int
        [Column, Nullable] public DateTime? dt_efetivo { get; set; } // datetime
    }

    [Table(Schema = "dbo", Name = "T_Empresa")]
    public partial class T_Empresa
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public string st_empresa { get; set; } // varchar(6)
        [Column, Nullable] public string nu_CNPJ { get; set; } // varchar(14)
        [Column, Nullable] public string st_fantasia { get; set; } // varchar(99)
        [Column, Nullable] public string st_social { get; set; } // varchar(99)
        [Column, Nullable] public string st_endereco { get; set; } // varchar(99)
        [Column, Nullable] public string st_cidade { get; set; } // varchar(99)
        [Column, Nullable] public string st_estado { get; set; } // varchar(2)
        [Column, Nullable] public string nu_CEP { get; set; } // varchar(14)
        [Column, Nullable] public string nu_telefone { get; set; } // varchar(20)
        [Column, Nullable] public int? nu_cartoes { get; set; } // int
        [Column, Nullable] public int? nu_parcelas { get; set; } // int
        [Column, Nullable] public char? tg_blocked { get; set; } // varchar(1)
        [Column, Nullable] public int? fk_admin { get; set; } // int
        [Column, Nullable] public string nu_contaDeb { get; set; } // varchar(20)
        [Column, Nullable] public int? vr_mensalidade { get; set; } // int
        [Column, Nullable] public int? nu_pctValor { get; set; } // int
        [Column, Nullable] public int? vr_transacao { get; set; } // int
        [Column, Nullable] public int? vr_minimo { get; set; } // int
        [Column, Nullable] public int? nu_franquia { get; set; } // int
        [Column, Nullable] public int? nu_periodoFat { get; set; } // int
        [Column, Nullable] public int? nu_diaVenc { get; set; } // int
        [Column, Nullable] public char? tg_tipoCobranca { get; set; } // varchar(1)
        [Column, Nullable] public int? nu_bancoFat { get; set; } // int
        [Column, Nullable] public int? vr_cartaoAtivo { get; set; } // int
        [Column, Nullable] public int? tg_isentoFat { get; set; } // int
        [Column, Nullable] public string st_obs { get; set; } // varchar(400)
        [Column, Nullable] public int? tg_bloq { get; set; } // int
        [Column, Nullable] public string st_homepage { get; set; } // varchar(500)
        [Column, Nullable] public int? nu_diaFech { get; set; } // int
        [Column, Nullable] public string st_horaFech { get; set; } // varchar(500)
        [Column, Nullable] public bool? tg_convenioComSaldo { get; set; } // varchar(500)
        [Column, Nullable] public long? fkParceiro { get; set; } // bigint
        [Column, Nullable] public string st_emailPlastico { get; set; } // varchar(500)
        [Column, Nullable] public bool? bContaCorrenteAssociado { get; set; } // varchar(500)
    }

    [Table(Schema = "dbo", Name = "T_EmpresaAfiliada")]
    public partial class T_EmpresaAfiliada
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public string st_nome { get; set; } // varchar(20)
        [Column, Nullable] public int? fk_empresa { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "T_ExtraGift")]
    public partial class T_ExtraGift
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public string st_nome { get; set; } // varchar(40)
        [Column, Nullable] public int? vr_valor { get; set; } // int
        [Column, Nullable] public int? fk_empresa { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "T_Faturamento")]
    public partial class T_Faturamento
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_empresa { get; set; } // int
        [Column, Nullable] public int? fk_loja { get; set; } // int
        [Column, Nullable] public int? vr_cobranca { get; set; } // int
        [Column, Nullable] public DateTime? dt_vencimento { get; set; } // datetime
        [Column, Nullable] public DateTime? dt_baixa { get; set; } // datetime
        [Column, Nullable] public char? tg_situacao { get; set; } // varchar(1)
        [Column, Nullable] public int? tg_retBanco { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "T_FaturamentoDetalhes")]
    public partial class T_FaturamentoDetalhe
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_fatura { get; set; } // int
        [Column, Nullable] public int? tg_tipoFat { get; set; } // int
        [Column, Nullable] public int? nu_quantidade { get; set; } // int
        [Column, Nullable] public int? vr_cobranca { get; set; } // int
        [Column, Nullable] public char? tg_desconto { get; set; } // varchar(1)
        [Column, Nullable] public string st_extras { get; set; } // varchar(100)
        [Column, Nullable] public int? fk_empresa { get; set; } // int
        [Column, Nullable] public int? fk_loja { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "T_InfoAdicionais")]
    public partial class T_InfoAdicionai
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public string st_codigo { get; set; } // varchar(6)
        [Column, Nullable] public string st_empresaAfiliada { get; set; } // varchar(30)
        [Column, Nullable] public string st_presenteado { get; set; } // varchar(50)
        [Column, Nullable] public string st_recado { get; set; } // varchar(80)
        [Column, Nullable] public DateTime? dt_edu_nasc { get; set; } // datetime
        [Column, Nullable] public char? st_edu_sexo { get; set; } // varchar(1)
        [Column, Nullable] public char? st_edu_grau { get; set; } // varchar(1)
        [Column, Nullable] public string st_edu_serie_semestre { get; set; } // varchar(2)
        [Column, Nullable] public string st_edu_turma { get; set; } // varchar(10)
        [Column, Nullable] public string st_edu_curso { get; set; } // varchar(30)
        [Column, Nullable] public DateTime? dt_edu_atualizacao { get; set; } // datetime
        [Column, Nullable] public string st_empresa { get; set; } // varchar(6)
        [Column, Nullable] public string st_matricula { get; set; } // varchar(6)
    }

    [Table(Schema = "dbo", Name = "T_Loja")]
    public partial class T_Loja
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public string nu_CNPJ { get; set; } // varchar(14)
        [Column, Nullable] public string st_nome { get; set; } // varchar(99)
        [Column, Nullable] public string st_social { get; set; } // varchar(99)
        [Column, Nullable] public string st_endereco { get; set; } // varchar(199)
        [Column, Nullable] public string st_enderecoInst { get; set; } // varchar(199)
        [Column, Nullable] public string nu_inscEst { get; set; } // varchar(20)
        [Column, Nullable] public string st_cidade { get; set; } // varchar(99)
        [Column, Nullable] public string st_estado { get; set; } // varchar(2)
        [Column, Nullable] public string nu_CEP { get; set; } // varchar(18)
        [Column, Nullable] public string nu_telefone { get; set; } // varchar(20)
        [Column, Nullable] public string nu_fax { get; set; } // varchar(20)
        [Column, Nullable] public string st_contato { get; set; } // varchar(40)
        [Column, Nullable] public int? vr_mensalidade { get; set; } // int
        [Column, Nullable] public string nu_contaDeb { get; set; } // varchar(20)
        [Column, Nullable] public string st_obs { get; set; } // varchar(900)
        [Column, Nullable] public string st_loja { get; set; } // varchar(40)
        [Column, Nullable] public char? tg_blocked { get; set; } // varchar(1)
        [Column, Nullable] public int? nu_pctValor { get; set; } // int
        [Column, Nullable] public int? vr_transacao { get; set; } // int
        [Column, Nullable] public int? vr_minimo { get; set; } // int
        [Column, Nullable] public int? nu_franquia { get; set; } // int
        [Column, Nullable] public int? nu_periodoFat { get; set; } // int
        [Column, Nullable] public int? nu_diavenc { get; set; } // int
        [Column, Nullable] public char? tg_tipoCobranca { get; set; } // varchar(1)
        [Column, Nullable] public int? nu_bancoFat { get; set; } // int
        [Column, Nullable] public int? tg_isentoFat { get; set; } // int
        [Column, Nullable] public string st_senha { get; set; } // varchar(16)
        [Column, Nullable] public int? tg_cancel { get; set; } // int
        [Column, Nullable] public int? tg_portalComSenha { get; set; } // int
        [Column, Nullable] public string st_email { get; set; } // varchar(200)
        [Column, Nullable] public string st_telCelular { get; set; } // varchar(20)
        [Column, Nullable] public long? fk_banco { get; set; }
        [Column, Nullable] public string st_agencia { get; set; } // varchar(20)
        [Column, Nullable] public string st_conta { get; set; } // varchar(20)
        [Column, Nullable] public string st_cpfResp { get; set; } // varchar(20)
        [Column, Nullable] public string st_dataResp { get; set; } // varchar(20)
    }

    [Table(Schema = "dbo", Name = "T_LojaMensagem")]
    public partial class T_LojaMensagem
    {
        [PrimaryKey, Identity] public long i_unique { get; set; } // bigint
        [Column, Nullable] public long? fk_loja { get; set; } // bigint
        [Column, Nullable] public string st_msg { get; set; } // varchar(999)
        [Column, Nullable] public string st_link { get; set; } // varchar(150)
        [Column, Nullable] public DateTime? dt_validade { get; set; } // datetime
        [Column, Nullable] public DateTime? dt_criacao { get; set; } // datetime
        [Column, Nullable] public bool? tg_ativa { get; set; } // bit
    }

    [Table(Schema = "dbo", Name = "T_LoteCartao")]
    public partial class T_LoteCartao
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? nu_cartoes { get; set; } // int
        [Column, Nullable] public int? fk_empresa { get; set; } // int
        [Column, Nullable] public int? tg_sitLote { get; set; } // int
        [Column, Nullable] public DateTime? dt_abertura { get; set; } // datetime
        [Column, Nullable] public DateTime? dt_envio_grafica { get; set; } // datetime
        [Column, Nullable] public DateTime? dt_ativacao { get; set; } // datetime
    }

    [Table(Schema = "dbo", Name = "T_LoteCartaoDetalhe")]
    public partial class T_LoteCartaoDetalhe
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_lote { get; set; } // int
        [Column, Nullable] public int? fk_empresa { get; set; } // int
        [Column, Nullable] public int? fk_cartao { get; set; } // int
        [Column, Nullable] public int? nu_matricula { get; set; } // int
        [Column, Nullable] public int? nu_via_original { get; set; } // int
        [Column, Nullable] public int? nu_titularidade { get; set; } // int
        [Column, Nullable] public string nu_cpf { get; set; } // varchar(20)
        [Column, Nullable] public string st_nome_cartao { get; set; } // varchar(99)
        [Column, Nullable] public DateTime? dt_ativacao { get; set; } // datetime
        [Column, Nullable] public DateTime? dt_pedido { get; set; } // datetime
    }

    [Table(Schema = "dbo", Name = "T_MensagemEdu")]
    public partial class T_MensagemEdu
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public string st_mens { get; set; } // varchar(900)
        [Column, Nullable] public int? fk_empresa { get; set; } // int
        [Column, Nullable] public DateTime? dt_ini { get; set; } // datetime
        [Column, Nullable] public DateTime? dt_fim { get; set; } // datetime
    }

    [Table(Schema = "dbo", Name = "T_Parcelas")]
    public partial class T_Parcela
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? nu_nsu { get; set; } // int
        [Column, Nullable] public int? fk_empresa { get; set; } // int
        [Column, Nullable] public int? fk_cartao { get; set; } // int
        [Column, Nullable] public DateTime? dt_inclusao { get; set; } // datetime
        [Column, Nullable] public int? nu_parcela { get; set; } // int
        [Column, Nullable] public int? vr_valor { get; set; } // int
        [Column, Nullable] public int? nu_indice { get; set; } // int
        [Column, Nullable] public char? tg_pago { get; set; } // varchar(1)
        [Column, Nullable] public int? fk_loja { get; set; } // int
        [Column, Nullable] public int? nu_tot_parcelas { get; set; } // int
        [Column, Nullable] public int? fk_terminal { get; set; } // int
        [Column, Nullable] public int? fk_log_transacoes { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "T_PayFone")]
    public partial class T_PayFone
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public string st_telefone { get; set; } // varchar(10)
        [Column, Nullable] public char? tg_tipoCelular { get; set; } // varchar(1)
        [Column, Nullable] public int? fk_cartao { get; set; } // int
        [Column, Nullable] public int? fk_terminal { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "T_PendPayFone")]
    public partial class T_PendPayFone
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_cartao { get; set; } // int
        [Column, Nullable] public int? fk_terminal { get; set; } // int
        [Column, Nullable] public int? nu_nsu { get; set; } // int
        [Column, Nullable] public int? vr_valor { get; set; } // int
        [Column, Nullable] public DateTime? dt_inclusao { get; set; } // datetime
        [Column, Nullable] public char? en_situacao { get; set; } // varchar(1)
        [Column, Nullable] public int? fk_empresa { get; set; } // int
        [Column, Nullable] public int? fk_loja { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "T_Proprietario")]
    public partial class T_Proprietario
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public string st_cpf { get; set; } // varchar(20)
        [Column, Nullable] public string st_nome { get; set; } // varchar(99)
        [Column, Nullable] public string st_endereco { get; set; } // varchar(900)
        [Column, Nullable] public string st_numero { get; set; } // varchar(29)
        [Column, Nullable] public string st_complemento { get; set; } // varchar(29)
        [Column, Nullable] public string st_bairro { get; set; } // varchar(99)
        [Column, Nullable] public string st_cidade { get; set; } // varchar(99)
        [Column, Nullable] public string st_UF { get; set; } // varchar(2)
        [Column, Nullable] public string st_cep { get; set; } // varchar(20)
        [Column, Nullable] public string st_ddd { get; set; } // varchar(3)
        [Column, Nullable] public string st_telefone { get; set; } // varchar(20)
        [Column, Nullable] public DateTime? dt_nasc { get; set; } // datetime
        [Column, Nullable] public string st_email { get; set; } // varchar(199)
        [Column, Nullable] public int? vr_renda { get; set; } // int
        [Column, Nullable] public string st_senhaEdu { get; set; } // varchar(16)
    }

    [Table(Schema = "dbo", Name = "T_Quiosque")]
    public partial class T_Quiosque
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_empresa { get; set; } // int
        [Column, Nullable] public string st_nome { get; set; } // varchar(40)
    }

    [Table(Schema = "dbo", Name = "T_RepasseLoja")]
    public partial class T_RepasseLoja
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? fk_loja { get; set; } // int
        [Column, Nullable] public int? tg_opcao { get; set; } // int
        [Column, Nullable] public int? vr_valor { get; set; } // int
        [Column, Nullable] public string st_ident { get; set; } // varchar(90)
        [Column, Nullable] public DateTime? dt_efetiva { get; set; } // datetime
    }

    [Table(Schema = "dbo", Name = "T_RetCobranca")]
    public partial class T_RetCobranca
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public int? nu_codBanco { get; set; } // int
        [Column, Nullable] public int? nu_cod { get; set; } // int
        [Column, Nullable] public char? tg_tipoCob { get; set; } // varchar(1)
        [Column, Nullable] public string st_codMsg { get; set; } // varchar(99)
    }

    [Table(Schema = "dbo", Name = "T_Terminal")]
    public partial class T_Terminal
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public string nu_terminal { get; set; } // varchar(12)
        [Column, Nullable] public int? fk_loja { get; set; } // int
        [Column, Nullable] public string st_localizacao { get; set; } // varchar(250)
    }

    [Table(Schema = "dbo", Name = "T_Usuario")]
    public partial class T_Usuario
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public char? tg_nivel { get; set; } // varchar(1)
        [Column, Nullable] public char? tg_logoff { get; set; } // varchar(1)
        [Column, Nullable] public DateTime? dt_trocaSenha { get; set; } // datetime
        [Column, Nullable] public DateTime? dt_ultUso { get; set; } // datetime
        [Column, Nullable] public int? nu_senhaErrada { get; set; } // int
        [Column, Nullable] public char? tg_trocaSenha { get; set; } // varchar(1)
        [Column, Nullable] public string st_senha_1 { get; set; } // varchar(64)
        [Column, Nullable] public string st_senha_2 { get; set; } // varchar(64)
        [Column, Nullable] public string st_senha_3 { get; set; } // varchar(64)
        [Column, Nullable] public string st_senha_4 { get; set; } // varchar(64)
        [Column, Nullable] public string st_senha_5 { get; set; } // varchar(64)
        [Column, Nullable] public string st_empresa { get; set; } // varchar(6)
        [Column, Nullable] public string st_senha { get; set; } // varchar(64)
        [Column, Nullable] public char? tg_bloqueio { get; set; } // varchar(1)
        [Column, Nullable] public string st_nome { get; set; } // varchar(20)
        [Column, Nullable] public int? fk_quiosque { get; set; } // int
        [Column, Nullable] public int? tg_aviso { get; set; } // int
        [Column, Nullable] public bool? bOperador { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "T_WebBlock")]
    public partial class T_WebBlock
    {
        [PrimaryKey, Identity] public decimal i_unique { get; set; } // numeric(15, 0)
        [Column, Nullable] public string st_ip { get; set; } // varchar(99)
        [Column, Nullable] public int? fk_cartao { get; set; } // int
        [Column, Nullable] public DateTime? dt_expire { get; set; } // datetime
    }

    public static partial class AutorizadorCNDBStoredProcedures
    {
        #region sp_alterdiagram

        public static int sp_alterdiagram(this DataConnection dataConnection, string @diagramname, int? @owner_id, int? @version, byte[] @definition)
        {
            return dataConnection.ExecuteProc("[dbo].[sp_alterdiagram]",
                new DataParameter("@diagramname", @diagramname, DataType.NVarChar),
                new DataParameter("@owner_id", @owner_id, DataType.Int32),
                new DataParameter("@version", @version, DataType.Int32),
                new DataParameter("@definition", @definition, DataType.VarBinary));
        }

        #endregion

        #region sp_creatediagram

        public static int sp_creatediagram(this DataConnection dataConnection, string @diagramname, int? @owner_id, int? @version, byte[] @definition)
        {
            return dataConnection.ExecuteProc("[dbo].[sp_creatediagram]",
                new DataParameter("@diagramname", @diagramname, DataType.NVarChar),
                new DataParameter("@owner_id", @owner_id, DataType.Int32),
                new DataParameter("@version", @version, DataType.Int32),
                new DataParameter("@definition", @definition, DataType.VarBinary));
        }

        #endregion

        #region sp_dropdiagram

        public static int sp_dropdiagram(this DataConnection dataConnection, string @diagramname, int? @owner_id)
        {
            return dataConnection.ExecuteProc("[dbo].[sp_dropdiagram]",
                new DataParameter("@diagramname", @diagramname, DataType.NVarChar),
                new DataParameter("@owner_id", @owner_id, DataType.Int32));
        }

        #endregion

        #region sp_helpdiagramdefinition

        public static IEnumerable<sp_helpdiagramdefinitionResult> sp_helpdiagramdefinition(this DataConnection dataConnection, string @diagramname, int? @owner_id)
        {
            return dataConnection.QueryProc<sp_helpdiagramdefinitionResult>("[dbo].[sp_helpdiagramdefinition]",
                new DataParameter("@diagramname", @diagramname, DataType.NVarChar),
                new DataParameter("@owner_id", @owner_id, DataType.Int32));
        }

        public partial class sp_helpdiagramdefinitionResult
        {
            public int? version { get; set; }
            public byte[] definition { get; set; }
        }

        #endregion

        #region sp_helpdiagrams

        public static IEnumerable<sp_helpdiagramsResult> sp_helpdiagrams(this DataConnection dataConnection, string @diagramname, int? @owner_id)
        {
            return dataConnection.QueryProc<sp_helpdiagramsResult>("[dbo].[sp_helpdiagrams]",
                new DataParameter("@diagramname", @diagramname, DataType.NVarChar),
                new DataParameter("@owner_id", @owner_id, DataType.Int32));
        }

        public partial class sp_helpdiagramsResult
        {
            public string Database { get; set; }
            public string Name { get; set; }
            public int ID { get; set; }
            public string Owner { get; set; }
            public int OwnerID { get; set; }
        }

        #endregion

        #region sp_renamediagram

        public static int sp_renamediagram(this DataConnection dataConnection, string @diagramname, int? @owner_id, string @new_diagramname)
        {
            return dataConnection.ExecuteProc("[dbo].[sp_renamediagram]",
                new DataParameter("@diagramname", @diagramname, DataType.NVarChar),
                new DataParameter("@owner_id", @owner_id, DataType.Int32),
                new DataParameter("@new_diagramname", @new_diagramname, DataType.NVarChar));
        }

        #endregion
    }

    public static partial class SqlFunctions
    {
        #region fn_diagramobjects

        [Sql.Function(Name = "dbo.fn_diagramobjects", ServerSideOnly = true)]
        public static int? fn_diagramobjects()
        {
            throw new InvalidOperationException();
        }

        #endregion
    }

    public static partial class TableExtensions
    {
        public static I_Batch Find(this ITable<I_Batch> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static i_patch Find(this ITable<i_patch> table, int i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static I_Scheduler Find(this ITable<I_Scheduler> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static LINK_Agendum Find(this ITable<LINK_Agendum> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static LINK_Edu_FundoEmpresa Find(this ITable<LINK_Edu_FundoEmpresa> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static LINK_LojaEmpresa Find(this ITable<LINK_LojaEmpresa> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static LINK_PFAtivacao Find(this ITable<LINK_PFAtivacao> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static LINK_ProprietarioCartao Find(this ITable<LINK_ProprietarioCartao> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static LINK_RepasseParcela Find(this ITable<LINK_RepasseParcela> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static LINK_UsuarioTerminal Find(this ITable<LINK_UsuarioTerminal> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static LOG_Audit Find(this ITable<LOG_Audit> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static LOG_Chamado Find(this ITable<LOG_Chamado> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static LOG_Edu_RendimentoEmpresa Find(this ITable<LOG_Edu_RendimentoEmpresa> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static LOG_Fechamento Find(this ITable<LOG_Fechamento> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static LOG_GiftRange Find(this ITable<LOG_GiftRange> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static LOG_NS_FAT Find(this ITable<LOG_NS_FAT> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static LOG_NSA Find(this ITable<LOG_NSA> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static LOG_NSU Find(this ITable<LOG_NSU> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static LOG_Transaco Find(this ITable<LOG_Transaco> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static LOG_VendaCartaoGift Find(this ITable<LOG_VendaCartaoGift> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static LOG_VendaProdutoGift Find(this ITable<LOG_VendaProdutoGift> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_BoletoEdu Find(this ITable<T_BoletoEdu> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_Cartao Find(this ITable<T_Cartao> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_Chamado Find(this ITable<T_Chamado> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_ChequesGift Find(this ITable<T_ChequesGift> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_Dependente Find(this ITable<T_Dependente> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_Edu_AplicacaoVirtual Find(this ITable<T_Edu_AplicacaoVirtual> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_Edu_EmpresaVirtual Find(this ITable<T_Edu_EmpresaVirtual> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_Edu_FundoEmpresa Find(this ITable<T_Edu_FundoEmpresa> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_Empresa Find(this ITable<T_Empresa> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_EmpresaAfiliada Find(this ITable<T_EmpresaAfiliada> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_ExtraGift Find(this ITable<T_ExtraGift> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_Faturamento Find(this ITable<T_Faturamento> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_FaturamentoDetalhe Find(this ITable<T_FaturamentoDetalhe> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_InfoAdicionai Find(this ITable<T_InfoAdicionai> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_Loja Find(this ITable<T_Loja> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_LojaMensagem Find(this ITable<T_LojaMensagem> table, long i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_LoteCartao Find(this ITable<T_LoteCartao> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_LoteCartaoDetalhe Find(this ITable<T_LoteCartaoDetalhe> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_MensagemEdu Find(this ITable<T_MensagemEdu> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_Parcela Find(this ITable<T_Parcela> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_PayFone Find(this ITable<T_PayFone> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_PendPayFone Find(this ITable<T_PendPayFone> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_Proprietario Find(this ITable<T_Proprietario> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_Quiosque Find(this ITable<T_Quiosque> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_RepasseLoja Find(this ITable<T_RepasseLoja> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_RetCobranca Find(this ITable<T_RetCobranca> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_Terminal Find(this ITable<T_Terminal> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_Usuario Find(this ITable<T_Usuario> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }

        public static T_WebBlock Find(this ITable<T_WebBlock> table, decimal i_unique)
        {
            return table.FirstOrDefault(t =>
                t.i_unique == i_unique);
        }
    }
}
