TRUNCATE TABLE public."AuditLog" RESTART IDENTITY;
TRUNCATE TABLE public."Cidade" RESTART IDENTITY;
TRUNCATE TABLE public."CompanyNews" RESTART IDENTITY;
TRUNCATE TABLE public."Estado" RESTART IDENTITY;
TRUNCATE TABLE public."Profile" RESTART IDENTITY;
TRUNCATE TABLE public."Project" RESTART IDENTITY;
TRUNCATE TABLE public."ProjectPhase" RESTART IDENTITY;
TRUNCATE TABLE public."ProjectSprint" RESTART IDENTITY;
TRUNCATE TABLE public."ProjectSprintVersion" RESTART IDENTITY;
TRUNCATE TABLE public."ProjectUser" RESTART IDENTITY;
TRUNCATE TABLE public."Survey" RESTART IDENTITY;
TRUNCATE TABLE public."SurveyOption" RESTART IDENTITY;
TRUNCATE TABLE public."SurveyUserOption" RESTART IDENTITY;
TRUNCATE TABLE public."Task" RESTART IDENTITY;
TRUNCATE TABLE public."TaskAccumulatorValue" RESTART IDENTITY;
TRUNCATE TABLE public."TaskCategory" RESTART IDENTITY;
TRUNCATE TABLE public."TaskCheckPoint" RESTART IDENTITY;
TRUNCATE TABLE public."TaskCheckPointMark" RESTART IDENTITY;
TRUNCATE TABLE public."TaskCustomStep" RESTART IDENTITY;
TRUNCATE TABLE public."TaskDependency" RESTART IDENTITY;
TRUNCATE TABLE public."TaskFlow" RESTART IDENTITY;
TRUNCATE TABLE public."TaskFlowChange" RESTART IDENTITY;
TRUNCATE TABLE public."TaskMessage" RESTART IDENTITY;
TRUNCATE TABLE public."TaskProgress" RESTART IDENTITY;
TRUNCATE TABLE public."TaskQuestion" RESTART IDENTITY;
TRUNCATE TABLE public."TaskType" RESTART IDENTITY;
TRUNCATE TABLE public."TaskTypeAccumulator" RESTART IDENTITY;
TRUNCATE TABLE public."User" RESTART IDENTITY;
TRUNCATE TABLE public."UserEmail" RESTART IDENTITY;
TRUNCATE TABLE public."UserNewsRead" RESTART IDENTITY;
TRUNCATE TABLE public."UserPhone" RESTART IDENTITY;
TRUNCATE TABLE public."Associado" RESTART IDENTITY;
TRUNCATE TABLE public."AssociadoEmail" RESTART IDENTITY;
TRUNCATE TABLE public."AssociadoTelefone" RESTART IDENTITY;
TRUNCATE TABLE public."AssociadoEndereco" RESTART IDENTITY;
TRUNCATE TABLE public."AssociadoEndereco" RESTART IDENTITY;
TRUNCATE TABLE public."AssociadoContato" RESTART IDENTITY;
TRUNCATE TABLE public."AssociadoMensagem" RESTART IDENTITY;
TRUNCATE TABLE public."AssociadoCategoria" RESTART IDENTITY;
TRUNCATE TABLE public."AssociadoDependente" RESTART IDENTITY;
TRUNCATE TABLE public."Cidade" RESTART IDENTITY;
TRUNCATE TABLE public."Estado" RESTART IDENTITY;
TRUNCATE TABLE public."Empresa" RESTART IDENTITY;

TRUNCATE TABLE public."Especialidade" RESTART IDENTITY;
TRUNCATE TABLE public."Credenciado" RESTART IDENTITY;
TRUNCATE TABLE public."CredenciadoEmpresa" RESTART IDENTITY;
TRUNCATE TABLE public."CredenciadoEmail" RESTART IDENTITY;
TRUNCATE TABLE public."CredenciadoTelefone" RESTART IDENTITY;
TRUNCATE TABLE public."CredenciadoEndereco" RESTART IDENTITY;
TRUNCATE TABLE public."CredenciadoEmpresaTuss" RESTART IDENTITY;

TRUNCATE TABLE public."Procedimento" RESTART IDENTITY;
TRUNCATE TABLE public."Autorizacao" RESTART IDENTITY;
TRUNCATE TABLE public."Fechamento" RESTART IDENTITY;
TRUNCATE TABLE public."LoteGrafica" RESTART IDENTITY;
TRUNCATE TABLE public."LoteGraficaCartao" RESTART IDENTITY;




