//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModel
{
	/// <summary>
	/// Database       : SuporteCIT
	/// Data Source    : localhost
	/// Server Version : 9.6.1
	/// </summary>
	public partial class SuporteCITDB : LinqToDB.Data.DataConnection
	{
		public ITable<Perfil>          Perfils          { get { return this.GetTable<Perfil>(); } }
		public ITable<Usuario>         Usuarios         { get { return this.GetTable<Usuario>(); } }
		public ITable<UsuarioEmail>    UsuarioEmails    { get { return this.GetTable<UsuarioEmail>(); } }
		public ITable<UsuarioTelefone> UsuarioTelefones { get { return this.GetTable<UsuarioTelefone>(); } }

		public SuporteCITDB()
		{
		}

		public SuporteCITDB(string configuration)
			: base(configuration)
		{
		}
	}

	[Table(Schema="public", Name="Perfil")]
	public partial class Perfil
	{
		[PrimaryKey, Identity] public long   Id           { get; set; } // bigint
		[Column,     Nullable] public string StNome       { get; set; } // character varying(150)
		[Column,     Nullable] public string StPermissoes { get; set; } // character varying(4000)
	}

	[Table(Schema="public", Name="Usuario")]
	public partial class Usuario
	{
		[PrimaryKey, Identity] public long      Id            { get; set; } // bigint
		[Column,     Nullable] public string    StLogin       { get; set; } // character varying(100)
		[Column,     Nullable] public string    StPassword    { get; set; } // character varying(100)
		[Column,     Nullable] public bool?     bAtivo        { get; set; } // boolean
		[Column,     Nullable] public long?     FkPerfil      { get; set; } // bigint
		[Column,     Nullable] public DateTime? DtUltimoLogin { get; set; } // timestamp (6) without time zone
	}

	[Table(Schema="public", Name="UsuarioEmail")]
	public partial class UsuarioEmail
	{
		[PrimaryKey, Identity] public long   Id        { get; set; } // bigint
		[Column,     Nullable] public string StEmail   { get; set; } // character varying(250)
		[Column,     Nullable] public long?  FkUsuario { get; set; } // bigint
	}

	[Table(Schema="public", Name="UsuarioTelefone")]
	public partial class UsuarioTelefone
	{
		[PrimaryKey, Identity] public long   Id         { get; set; } // bigint
		[Column,     Nullable] public string StTelefone { get; set; } // character varying(20)
		[Column,     Nullable] public string StLocal    { get; set; } // character varying(100)
		[Column,     Nullable] public long?  FkUsuario  { get; set; } // bigint
	}

	public static partial class tableExtensions
	{
		public static Perfil Find(this ITable<Perfil> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Usuario Find(this ITable<Usuario> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UsuarioEmail Find(this ITable<UsuarioEmail> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UsuarioTelefone Find(this ITable<UsuarioTelefone> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}
